
name: 'Basic Test'

on:
  push:
    branches:
      - main

  pull_request:
    
jobs:
    test:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install-Clang-Format
              run: brew install clang-format
            - name: Check-Format
              run: ../../clang-format -i -style=file $(find . -name '*.cpp' -or -name '*.hpp')
