
name: 'Basic Test'

on:
  push:
    branches:
      - main

  pull_request:
    
jobs:
    test:
        runs-on: macos-latest
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Make-Executable
              run: chmod +x ./test1.sh
            - name: Run-Test
              run: ./test.sh
              
